# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/henry/code/pico16470

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/henry/code/pico16470

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/code/pico16470/CMakeFiles /home/henry/code/pico16470//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/henry/code/pico16470/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pico16470

# Build rule for target.
pico16470: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pico16470
.PHONY : pico16470

# fast build rule for target.
pico16470/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/build
.PHONY : pico16470/fast

#=============================================================================
# Target rules for targets named ELF2UF2Build

# Build rule for target.
ELF2UF2Build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ELF2UF2Build
.PHONY : ELF2UF2Build

# fast build rule for target.
ELF2UF2Build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ELF2UF2Build.dir/build.make CMakeFiles/ELF2UF2Build.dir/build
.PHONY : ELF2UF2Build/fast

#=============================================================================
# Target rules for targets named bs2_default

# Build rule for target.
bs2_default: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default
.PHONY : bs2_default

# fast build rule for target.
bs2_default/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default.dir/build
.PHONY : bs2_default/fast

#=============================================================================
# Target rules for targets named bs2_default_bin

# Build rule for target.
bs2_default_bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_bin
.PHONY : bs2_default_bin

# fast build rule for target.
bs2_default_bin/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_bin.dir/build
.PHONY : bs2_default_bin/fast

#=============================================================================
# Target rules for targets named bs2_default_padded_checksummed_asm

# Build rule for target.
bs2_default_padded_checksummed_asm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs2_default_padded_checksummed_asm
.PHONY : bs2_default_padded_checksummed_asm

# fast build rule for target.
bs2_default_padded_checksummed_asm/fast:
	$(MAKE) $(MAKESILENT) -f pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build.make pico-sdk/src/rp2_common/boot_stage2/CMakeFiles/bs2_default_padded_checksummed_asm.dir/build
.PHONY : bs2_default_padded_checksummed_asm/fast

home/henry/code/pico-sdk/src/common/pico_sync/critical_section.obj: home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.obj

home/henry/code/pico-sdk/src/common/pico_sync/critical_section.i: home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.i

home/henry/code/pico-sdk/src/common/pico_sync/critical_section.s: home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/critical_section.c.s

home/henry/code/pico-sdk/src/common/pico_sync/lock_core.obj: home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.obj

home/henry/code/pico-sdk/src/common/pico_sync/lock_core.i: home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.i

home/henry/code/pico-sdk/src/common/pico_sync/lock_core.s: home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/lock_core.c.s

home/henry/code/pico-sdk/src/common/pico_sync/mutex.obj: home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.obj

home/henry/code/pico-sdk/src/common/pico_sync/mutex.i: home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.i

home/henry/code/pico-sdk/src/common/pico_sync/mutex.s: home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/mutex.c.s

home/henry/code/pico-sdk/src/common/pico_sync/sem.obj: home/henry/code/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_sync/sem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/sem.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.c.obj

home/henry/code/pico-sdk/src/common/pico_sync/sem.i: home/henry/code/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_sync/sem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/sem.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.c.i

home/henry/code/pico-sdk/src/common/pico_sync/sem.s: home/henry/code/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_sync/sem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_sync/sem.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_sync/sem.c.s

home/henry/code/pico-sdk/src/common/pico_time/time.obj: home/henry/code/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_time/time.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/time.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.c.obj

home/henry/code/pico-sdk/src/common/pico_time/time.i: home/henry/code/pico-sdk/src/common/pico_time/time.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_time/time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/time.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.c.i

home/henry/code/pico-sdk/src/common/pico_time/time.s: home/henry/code/pico-sdk/src/common/pico_time/time.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_time/time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/time.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/time.c.s

home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.obj: home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.obj

home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.i: home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.i

home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.s: home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.c.s

home/henry/code/pico-sdk/src/common/pico_util/datetime.obj: home/henry/code/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_util/datetime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/datetime.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.c.obj

home/henry/code/pico-sdk/src/common/pico_util/datetime.i: home/henry/code/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_util/datetime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/datetime.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.c.i

home/henry/code/pico-sdk/src/common/pico_util/datetime.s: home/henry/code/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_util/datetime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/datetime.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/datetime.c.s

home/henry/code/pico-sdk/src/common/pico_util/pheap.obj: home/henry/code/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_util/pheap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/pheap.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.c.obj

home/henry/code/pico-sdk/src/common/pico_util/pheap.i: home/henry/code/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_util/pheap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/pheap.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.c.i

home/henry/code/pico-sdk/src/common/pico_util/pheap.s: home/henry/code/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_util/pheap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/pheap.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/pheap.c.s

home/henry/code/pico-sdk/src/common/pico_util/queue.obj: home/henry/code/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.obj

# target to build an object file
home/henry/code/pico-sdk/src/common/pico_util/queue.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/queue.c.obj
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.c.obj

home/henry/code/pico-sdk/src/common/pico_util/queue.i: home/henry/code/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/common/pico_util/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/queue.c.i
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.c.i

home/henry/code/pico-sdk/src/common/pico_util/queue.s: home/henry/code/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/common/pico_util/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/common/pico_util/queue.c.s
.PHONY : home/henry/code/pico-sdk/src/common/pico_util/queue.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.i: home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.s: home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.i: home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.s: home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.S.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.i: home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.s: home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.i: home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.s: home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.i: home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.s: home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.S.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.i: home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.s: home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.i: home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.s: home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.i: home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.s: home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.i: home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.s: home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.i: home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.s: home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.i: home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.s: home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.i: home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.s: home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i: home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s: home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c.s

home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj: home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.obj

home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.i: home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.i

home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.s: home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj: home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj: home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i: home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s: home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.obj: home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.i: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.s: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.obj: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.i: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.s: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj: home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.i: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.s: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.obj: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.i: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.s: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj: home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj: home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj: home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i: home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s: home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj: home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.obj: home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.i: home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.s: home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.obj: home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.i: home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.s: home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.obj: home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.i: home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.s: home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.S.obj

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.obj

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.i

home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s: home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp.s

home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.obj: home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.i: home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.s: home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj: home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i: home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s: home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.c.s

home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj: home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj

# target to build an object file
home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.obj

home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i: home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i

# target to preprocess a source file
home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.i

home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s: home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s

# target to generate assembly for a file
home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s
.PHONY : home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.c.s

src/imu.obj: src/imu.c.obj
.PHONY : src/imu.obj

# target to build an object file
src/imu.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/imu.c.obj
.PHONY : src/imu.c.obj

src/imu.i: src/imu.c.i
.PHONY : src/imu.i

# target to preprocess a source file
src/imu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/imu.c.i
.PHONY : src/imu.c.i

src/imu.s: src/imu.c.s
.PHONY : src/imu.s

# target to generate assembly for a file
src/imu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/imu.c.s
.PHONY : src/imu.c.s

src/main.obj: src/main.c.obj
.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/main.c.s
.PHONY : src/main.c.s

src/reg.obj: src/reg.c.obj
.PHONY : src/reg.obj

# target to build an object file
src/reg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/reg.c.obj
.PHONY : src/reg.c.obj

src/reg.i: src/reg.c.i
.PHONY : src/reg.i

# target to preprocess a source file
src/reg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/reg.c.i
.PHONY : src/reg.c.i

src/reg.s: src/reg.c.s
.PHONY : src/reg.s

# target to generate assembly for a file
src/reg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/reg.c.s
.PHONY : src/reg.c.s

src/script.obj: src/script.c.obj
.PHONY : src/script.obj

# target to build an object file
src/script.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/script.c.obj
.PHONY : src/script.c.obj

src/script.i: src/script.c.i
.PHONY : src/script.i

# target to preprocess a source file
src/script.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/script.c.i
.PHONY : src/script.c.i

src/script.s: src/script.c.s
.PHONY : src/script.s

# target to generate assembly for a file
src/script.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/script.c.s
.PHONY : src/script.c.s

src/usb.obj: src/usb.c.obj
.PHONY : src/usb.obj

# target to build an object file
src/usb.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/usb.c.obj
.PHONY : src/usb.c.obj

src/usb.i: src/usb.c.i
.PHONY : src/usb.i

# target to preprocess a source file
src/usb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/usb.c.i
.PHONY : src/usb.c.i

src/usb.s: src/usb.c.s
.PHONY : src/usb.s

# target to generate assembly for a file
src/usb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pico16470.dir/build.make CMakeFiles/pico16470.dir/src/usb.c.s
.PHONY : src/usb.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ELF2UF2Build"
	@echo "... bs2_default_bin"
	@echo "... bs2_default_padded_checksummed_asm"
	@echo "... bs2_default"
	@echo "... pico16470"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/critical_section.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/critical_section.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/critical_section.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/lock_core.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/lock_core.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/lock_core.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/mutex.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/mutex.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/mutex.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/sem.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/sem.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_sync/sem.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/time.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/time.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/time.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_time/timeout_helper.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/datetime.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/datetime.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/datetime.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/pheap.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/pheap.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/pheap.s"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/queue.obj"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/queue.i"
	@echo "... home/henry/code/pico-sdk/src/common/pico_util/queue.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_claim/claim.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_clocks/clocks.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_divider/divider.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_dma/dma.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_gpio/gpio.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_irq/irq_handler_chain.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pio/pio.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_pll/pll.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_spi/spi.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_sync/sync.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_timer/timer.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_uart/uart.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_vreg/vreg.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/hardware_xosc/xosc.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_bit_ops/bit_ops_aeabi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_bootrom/bootrom.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_divider/divider.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_aeabi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_init_rom.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_math.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_double/double_v1_rom_shim.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_aeabi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_init_rom.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_math.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_float/float_v1_rom_shim.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_malloc/pico_malloc.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_platform/platform.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_printf/printf.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_runtime/runtime.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/binary_info.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/crt0.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_standard_link/new_delete.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio/stdio.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdio_uart/stdio_uart.s"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.obj"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.i"
	@echo "... home/henry/code/pico-sdk/src/rp2_common/pico_stdlib/stdlib.s"
	@echo "... src/imu.obj"
	@echo "... src/imu.i"
	@echo "... src/imu.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/reg.obj"
	@echo "... src/reg.i"
	@echo "... src/reg.s"
	@echo "... src/script.obj"
	@echo "... src/script.i"
	@echo "... src/script.s"
	@echo "... src/usb.obj"
	@echo "... src/usb.i"
	@echo "... src/usb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

